train:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/audio/val"
  video_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/mouths"

  # data_dir: "/kaggle/input/librispeech"
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/audio/val"
  video_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/mouths"
