test:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/audio/val"
  video_dir: "/root/dataset/dla_dataset/mouths"