test:
  _target_: src.datasets.CustomDirDataset
  dataset_name : custom_dataset_test
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "dla_dataset/audio/test"
  mouth_path: "data/dla_dataset/mouths"
