test:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_test
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "dla_dataset/audio/test"
  video_path: "data/dla_dataset/mouths"
