train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  min_audio_length: 2.0
  max_audio_length: 10.0
  max_text_length: 200
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 5.0
  max_text_length: 200
  limit: 10
  instance_transforms: ${transforms.instance_transforms.inference}
