train:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: 32
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "data/dla_dataset/audio/train"
  mouth_path: "data/dla_dataset/mouths"
# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: 32
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "data/dla_dataset/audio/val"
  mouth_path: "data/dla_dataset/mouths"
