train:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_train
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "/home/dlamaster/data/dla_dataset/audio/train"
  # data_path: "/home/atem/HSE_videos/4_DLA/hw_2_SeppechSep/dla_dataset/audio/train"
  # mouths_dir

# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "/home/dlamaster/data/dla_dataset/audio/val"
