train:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_train
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "/kaggle/input/dla-dataset/dla_dataset/audio/train"
  video_path: "/kaggle/input/dla-dataset/dla_dataset/mouths"
  # mouths_dir

# we filter partitions in one batch test to check the pipeline
# do not filter test dataset, you want to evaluate on the whole dataset
val:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "/kaggle/input/dla-dataset/dla_dataset/audio/val"
  video_path: "/kaggle/input/dla-dataset/dla_dataset/mouths"
