train:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_train
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}
  data_path: "data/dla_dataset/audio/train"
  video_path: "data/dla_dataset/mouths"

val:
  _target_: src.datasets.CustomDirAudioDataset
  dataset_name : custom_dataset_val
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
  data_path: "data/dla_dataset/audio/val"
  video_path: "data/dla_dataset/mouths"
