_target_: src.model.DTTNetPlusModel
g: 32
n_sources: 2
n_layers: 3
n_idp_layers: 4
n_heads: 2
video_embed_dim: 256
use_checkpoints: False
video_enc_weights_path: null # path to pretraind video_encoder waights
n_fft: ${transforms.instance_transforms.train.get_spectrogram.n_fft}
hop_length: ${transforms.instance_transforms.train.get_spectrogram.hop_length}
freeze_params: null # list of parameters (modules) or 'all' / null
unfreeze_params: null # list of parameters or null
