_target_: src.model.DTTwRTFSNet
g: 32
n_sources: 2
n_layers: 3
n_idp_layers: 4
n_heads: 2
q_video: 4
video_embed_dim: 512
hidden_dim: 64
caf_n_heads: 4
use_checkpoints: True
n_fft: ${transforms.instance_transforms.train.get_spectrogram.n_fft}
hop_length: ${transforms.instance_transforms.train.get_spectrogram.hop_length}
