defaults:
  - model: dttnet
  - metrics: inference
  - datasets: inference
  - dataloader: baseline
  - transforms: baseline
  - _self_

model_loader:
  from_pretrained: null

inferencer:
  device_tensors: ["spectrogram", "phase", "sources", "audio", "audio_length", "video"]
  device: auto
  save_path: "inferencer_results"
  seed: 1
