defaults:
  - model: dttnet_plus
  - metrics: inference
  - datasets: inference # we do not want to run inference on training data
  - dataloader: baseline
  - transforms: only_instance
  - _self_

model_loader:
  from_pretrained: "areshx/source-sep@dttnet_plus_video"
inferencer:
  device_tensors: ["spectrogram", "phase", "sources", "audio", "audio_length", "video"]
  device: auto # device name or "auto"
  save_path: "inferencer_test" # any name here, can be a dataset name
  seed: 1